### ISSUE TITLE
Not able to use script-sync from incognito browser.

### ISSUE THREAD

**Issue by CGraabaek** [arnoudkooi/sn-scriptsync#35]
When truing to use the script-sync from an incognito browser it doesn't work. 

It works the first time, when hitting the save icon from a script and it gets synced to VS Code as it should, but if I try to save from VS Code, it'll save "no valid token".

**Comment by CGraabaek** [comment]
Error from the SN Scipt Sync Helper Tab

```
{"error":{"detail":"Required to provide Auth information","message":"User Not Authenticated"},"status":"failure"}
```

**Comment by arnoudkooi** [comment]
Confirmed it doesnt work, looking at below I think I'll add something to the FAQ section.
As it doenst seem a good idea to change the manifest of the extension.
(did you consider using another profile instead of incognito?)

https://stackoverflow.com/questions/17531848/access-extension-file-in-incognito

**Comment by CGraabaek** [comment]
I use another profile myself, but for some reason had to use incognito and noticed that i couldn't use the extension at the same time.
